spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/spring3
    username: spring3
    password: spring3password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
debug: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug
