spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/spring3
    username: spring3
    password: spring3password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
